/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AboutModel
 */
export interface AboutModel {
    /**
     * 
     * @type {string}
     * @memberof AboutModel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutModel
     */
    about?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutModel
     */
    version?: string;
}

/**
 * Check if a given object implements the AboutModel interface.
 */
export function instanceOfAboutModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AboutModelFromJSON(json: any): AboutModel {
    return AboutModelFromJSONTyped(json, false);
}

export function AboutModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AboutModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'about': !exists(json, 'about') ? undefined : json['about'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function AboutModelToJSON(value?: AboutModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'about': value.about,
        'version': value.version,
    };
}

