/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DcmtkCore
 */
export interface DcmtkCore {
    /**
     * 
     * @type {string}
     * @memberof DcmtkCore
     */
    storescu: string;
    /**
     * 
     * @type {string}
     * @memberof DcmtkCore
     */
    storescp: string;
    /**
     * 
     * @type {string}
     * @memberof DcmtkCore
     */
    findscu: string;
    /**
     * 
     * @type {string}
     * @memberof DcmtkCore
     */
    movescu: string;
    /**
     * 
     * @type {string}
     * @memberof DcmtkCore
     */
    echoscu: string;
    /**
     * 
     * @type {string}
     * @memberof DcmtkCore
     */
    receiver: string;
}

/**
 * Check if a given object implements the DcmtkCore interface.
 */
export function instanceOfDcmtkCore(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "storescu" in value;
    isInstance = isInstance && "storescp" in value;
    isInstance = isInstance && "findscu" in value;
    isInstance = isInstance && "movescu" in value;
    isInstance = isInstance && "echoscu" in value;
    isInstance = isInstance && "receiver" in value;

    return isInstance;
}

export function DcmtkCoreFromJSON(json: any): DcmtkCore {
    return DcmtkCoreFromJSONTyped(json, false);
}

export function DcmtkCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): DcmtkCore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'storescu': json['storescu'],
        'storescp': json['storescp'],
        'findscu': json['findscu'],
        'movescu': json['movescu'],
        'echoscu': json['echoscu'],
        'receiver': json['receiver'],
    };
}

export function DcmtkCoreToJSON(value?: DcmtkCore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'storescu': value.storescu,
        'storescp': value.storescp,
        'findscu': value.findscu,
        'movescu': value.movescu,
        'echoscu': value.echoscu,
        'receiver': value.receiver,
    };
}

