/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DcmtkCore } from './DcmtkCore';
import {
    DcmtkCoreFromJSON,
    DcmtkCoreFromJSONTyped,
    DcmtkCoreToJSON,
} from './DcmtkCore';

/**
 * 
 * @export
 * @interface DcmtkDBPutModel
 */
export interface DcmtkDBPutModel {
    /**
     * 
     * @type {DcmtkCore}
     * @memberof DcmtkDBPutModel
     */
    info: DcmtkCore;
}

/**
 * Check if a given object implements the DcmtkDBPutModel interface.
 */
export function instanceOfDcmtkDBPutModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;

    return isInstance;
}

export function DcmtkDBPutModelFromJSON(json: any): DcmtkDBPutModel {
    return DcmtkDBPutModelFromJSONTyped(json, false);
}

export function DcmtkDBPutModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DcmtkDBPutModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': DcmtkCoreFromJSON(json['info']),
    };
}

export function DcmtkDBPutModelToJSON(value?: DcmtkDBPutModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': DcmtkCoreToJSON(value.info),
    };
}

