/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DcmtkCore } from './DcmtkCore';
import {
    DcmtkCoreFromJSON,
    DcmtkCoreFromJSONTyped,
    DcmtkCoreToJSON,
} from './DcmtkCore';
import type { ModelsListenerModelTime } from './ModelsListenerModelTime';
import {
    ModelsListenerModelTimeFromJSON,
    ModelsListenerModelTimeFromJSONTyped,
    ModelsListenerModelTimeToJSON,
} from './ModelsListenerModelTime';

/**
 * 
 * @export
 * @interface DcmtkDBReturnModel
 */
export interface DcmtkDBReturnModel {
    /**
     * 
     * @type {DcmtkCore}
     * @memberof DcmtkDBReturnModel
     */
    info: DcmtkCore;
    /**
     * 
     * @type {ModelsListenerModelTime}
     * @memberof DcmtkDBReturnModel
     */
    timeCreated: ModelsListenerModelTime;
    /**
     * 
     * @type {ModelsListenerModelTime}
     * @memberof DcmtkDBReturnModel
     */
    timeModified: ModelsListenerModelTime;
    /**
     * 
     * @type {string}
     * @memberof DcmtkDBReturnModel
     */
    message: string;
}

/**
 * Check if a given object implements the DcmtkDBReturnModel interface.
 */
export function instanceOfDcmtkDBReturnModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;
    isInstance = isInstance && "timeCreated" in value;
    isInstance = isInstance && "timeModified" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DcmtkDBReturnModelFromJSON(json: any): DcmtkDBReturnModel {
    return DcmtkDBReturnModelFromJSONTyped(json, false);
}

export function DcmtkDBReturnModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DcmtkDBReturnModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': DcmtkCoreFromJSON(json['info']),
        'timeCreated': ModelsListenerModelTimeFromJSON(json['time_created']),
        'timeModified': ModelsListenerModelTimeFromJSON(json['time_modified']),
        'message': json['message'],
    };
}

export function DcmtkDBReturnModelToJSON(value?: DcmtkDBReturnModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': DcmtkCoreToJSON(value.info),
        'time_created': ModelsListenerModelTimeToJSON(value.timeCreated),
        'time_modified': ModelsListenerModelTimeToJSON(value.timeModified),
        'message': value.message,
    };
}

