/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Not actually a DICOM, just some JSON.
 * @export
 * @interface Dicom
 */
export interface Dicom {
    /**
     * A longer sentence about nothing much
     * @type {string}
     * @memberof Dicom
     */
    aCoolPicture?: string;
}

/**
 * Check if a given object implements the Dicom interface.
 */
export function instanceOfDicom(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DicomFromJSON(json: any): Dicom {
    return DicomFromJSONTyped(json, false);
}

export function DicomFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dicom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aCoolPicture': !exists(json, 'a_cool_picture') ? undefined : json['a_cool_picture'],
    };
}

export function DicomToJSON(value?: Dicom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a_cool_picture': value.aCoolPicture,
    };
}

