/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Simply echo back whatever is POSTed to this API endpoing
 * @export
 * @interface EchoModel
 */
export interface EchoModel {
    /**
     * 
     * @type {string}
     * @memberof EchoModel
     */
    msg: string;
}

/**
 * Check if a given object implements the EchoModel interface.
 */
export function instanceOfEchoModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "msg" in value;

    return isInstance;
}

export function EchoModelFromJSON(json: any): EchoModel {
    return EchoModelFromJSONTyped(json, false);
}

export function EchoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EchoModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': json['msg'],
    };
}

export function EchoModelToJSON(value?: EchoModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
    };
}

