/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EchoModel } from './EchoModel';
import {
    EchoModelFromJSON,
    EchoModelFromJSONTyped,
    EchoModelToJSON,
} from './EchoModel';
import type { SysInfoModel } from './SysInfoModel';
import {
    SysInfoModelFromJSON,
    SysInfoModelFromJSONTyped,
    SysInfoModelToJSON,
} from './SysInfoModel';

/**
 * The model describing the relevant "hello" data
 * @export
 * @interface HelloModel
 */
export interface HelloModel {
    /**
     * 
     * @type {string}
     * @memberof HelloModel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof HelloModel
     */
    version?: string;
    /**
     * 
     * @type {SysInfoModel}
     * @memberof HelloModel
     */
    sysinfo?: SysInfoModel;
    /**
     * 
     * @type {EchoModel}
     * @memberof HelloModel
     */
    echoBack?: EchoModel;
}

/**
 * Check if a given object implements the HelloModel interface.
 */
export function instanceOfHelloModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HelloModelFromJSON(json: any): HelloModel {
    return HelloModelFromJSONTyped(json, false);
}

export function HelloModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'sysinfo': !exists(json, 'sysinfo') ? undefined : SysInfoModelFromJSON(json['sysinfo']),
        'echoBack': !exists(json, 'echoBack') ? undefined : EchoModelFromJSON(json['echoBack']),
    };
}

export function HelloModelToJSON(value?: HelloModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
        'sysinfo': SysInfoModelToJSON(value.sysinfo),
        'echoBack': EchoModelToJSON(value.echoBack),
    };
}

