/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListenerHandlerStatus
 */
export interface ListenerHandlerStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ListenerHandlerStatus
     */
    status: boolean;
}

/**
 * Check if a given object implements the ListenerHandlerStatus interface.
 */
export function instanceOfListenerHandlerStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ListenerHandlerStatusFromJSON(json: any): ListenerHandlerStatus {
    return ListenerHandlerStatusFromJSONTyped(json, false);
}

export function ListenerHandlerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListenerHandlerStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ListenerHandlerStatusToJSON(value?: ListenerHandlerStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

