/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsSmdbSetupModelValueStr
 */
export interface ModelsSmdbSetupModelValueStr {
    /**
     * 
     * @type {string}
     * @memberof ModelsSmdbSetupModelValueStr
     */
    value?: string;
}

/**
 * Check if a given object implements the ModelsSmdbSetupModelValueStr interface.
 */
export function instanceOfModelsSmdbSetupModelValueStr(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsSmdbSetupModelValueStrFromJSON(json: any): ModelsSmdbSetupModelValueStr {
    return ModelsSmdbSetupModelValueStrFromJSONTyped(json, false);
}

export function ModelsSmdbSetupModelValueStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsSmdbSetupModelValueStr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ModelsSmdbSetupModelValueStrToJSON(value?: ModelsSmdbSetupModelValueStr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

