/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsPacsQRmodelValueStr
 */
export interface ModelsPacsQRmodelValueStr {
    /**
     * 
     * @type {string}
     * @memberof ModelsPacsQRmodelValueStr
     */
    value?: string;
}

/**
 * Check if a given object implements the ModelsPacsQRmodelValueStr interface.
 */
export function instanceOfModelsPacsQRmodelValueStr(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsPacsQRmodelValueStrFromJSON(json: any): ModelsPacsQRmodelValueStr {
    return ModelsPacsQRmodelValueStrFromJSONTyped(json, false);
}

export function ModelsPacsQRmodelValueStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPacsQRmodelValueStr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ModelsPacsQRmodelValueStrToJSON(value?: ModelsPacsQRmodelValueStr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

