/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A simple model that has a time string field
 * @export
 * @interface ModelsPacsSetupModelTime
 */
export interface ModelsPacsSetupModelTime {
    /**
     * 
     * @type {string}
     * @memberof ModelsPacsSetupModelTime
     */
    time: string;
}

/**
 * Check if a given object implements the ModelsPacsSetupModelTime interface.
 */
export function instanceOfModelsPacsSetupModelTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "time" in value;

    return isInstance;
}

export function ModelsPacsSetupModelTimeFromJSON(json: any): ModelsPacsSetupModelTime {
    return ModelsPacsSetupModelTimeFromJSONTyped(json, false);
}

export function ModelsPacsSetupModelTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPacsSetupModelTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': json['time'],
    };
}

export function ModelsPacsSetupModelTimeToJSON(value?: ModelsPacsSetupModelTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
    };
}

