/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsListenerModelValueStr
 */
export interface ModelsListenerModelValueStr {
    /**
     * 
     * @type {string}
     * @memberof ModelsListenerModelValueStr
     */
    value?: string;
}

/**
 * Check if a given object implements the ModelsListenerModelValueStr interface.
 */
export function instanceOfModelsListenerModelValueStr(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsListenerModelValueStrFromJSON(json: any): ModelsListenerModelValueStr {
    return ModelsListenerModelValueStrFromJSONTyped(json, false);
}

export function ModelsListenerModelValueStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsListenerModelValueStr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ModelsListenerModelValueStrToJSON(value?: ModelsListenerModelValueStr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

