/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PACSsetupCore } from './PACSsetupCore';
import {
    PACSsetupCoreFromJSON,
    PACSsetupCoreFromJSONTyped,
    PACSsetupCoreToJSON,
} from './PACSsetupCore';

/**
 * Model that illustrates what to PUT to the DB
 * @export
 * @interface PACSdbPutModel
 */
export interface PACSdbPutModel {
    /**
     * 
     * @type {PACSsetupCore}
     * @memberof PACSdbPutModel
     */
    info: PACSsetupCore;
}

/**
 * Check if a given object implements the PACSdbPutModel interface.
 */
export function instanceOfPACSdbPutModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;

    return isInstance;
}

export function PACSdbPutModelFromJSON(json: any): PACSdbPutModel {
    return PACSdbPutModelFromJSONTyped(json, false);
}

export function PACSdbPutModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PACSdbPutModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': PACSsetupCoreFromJSON(json['info']),
    };
}

export function PACSdbPutModelToJSON(value?: PACSdbPutModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': PACSsetupCoreToJSON(value.info),
    };
}

