/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The PACS service model
 * @export
 * @interface PACSsetupCore
 */
export interface PACSsetupCore {
    /**
     * 
     * @type {string}
     * @memberof PACSsetupCore
     */
    aet?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSsetupCore
     */
    aetListener?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSsetupCore
     */
    aec?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSsetupCore
     */
    serverIP?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSsetupCore
     */
    serverPort?: string;
}

/**
 * Check if a given object implements the PACSsetupCore interface.
 */
export function instanceOfPACSsetupCore(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PACSsetupCoreFromJSON(json: any): PACSsetupCore {
    return PACSsetupCoreFromJSONTyped(json, false);
}

export function PACSsetupCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): PACSsetupCore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aet': !exists(json, 'aet') ? undefined : json['aet'],
        'aetListener': !exists(json, 'aet_listener') ? undefined : json['aet_listener'],
        'aec': !exists(json, 'aec') ? undefined : json['aec'],
        'serverIP': !exists(json, 'serverIP') ? undefined : json['serverIP'],
        'serverPort': !exists(json, 'serverPort') ? undefined : json['serverPort'],
    };
}

export function PACSsetupCoreToJSON(value?: PACSsetupCore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aet': value.aet,
        'aet_listener': value.aetListener,
        'aec': value.aec,
        'serverIP': value.serverIP,
        'serverPort': value.serverPort,
    };
}

