/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A model returned when an async PACS directive is indicated
 * @export
 * @interface PACSasync
 */
export interface PACSasync {
    /**
     * 
     * @type {string}
     * @memberof PACSasync
     */
    directiveType?: string;
    /**
     * 
     * @type {object}
     * @memberof PACSasync
     */
    response: object;
    /**
     * 
     * @type {string}
     * @memberof PACSasync
     */
    timestamp: string;
    /**
     * 
     * @type {object}
     * @memberof PACSasync
     */
    pACSdirective: object;
}

/**
 * Check if a given object implements the PACSasync interface.
 */
export function instanceOfPACSasync(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "pACSdirective" in value;

    return isInstance;
}

export function PACSasyncFromJSON(json: any): PACSasync {
    return PACSasyncFromJSONTyped(json, false);
}

export function PACSasyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): PACSasync {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'directiveType': !exists(json, 'directiveType') ? undefined : json['directiveType'],
        'response': json['response'],
        'timestamp': json['timestamp'],
        'pACSdirective': json['PACSdirective'],
    };
}

export function PACSasyncToJSON(value?: PACSasync | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'directiveType': value.directiveType,
        'response': value.response,
        'timestamp': value.timestamp,
        'PACSdirective': value.pACSdirective,
    };
}

