/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelsPacsSetupModelTime } from './ModelsPacsSetupModelTime';
import {
    ModelsPacsSetupModelTimeFromJSON,
    ModelsPacsSetupModelTimeFromJSONTyped,
    ModelsPacsSetupModelTimeToJSON,
} from './ModelsPacsSetupModelTime';
import type { PACSsetupCore } from './PACSsetupCore';
import {
    PACSsetupCoreFromJSON,
    PACSsetupCoreFromJSONTyped,
    PACSsetupCoreToJSON,
} from './PACSsetupCore';

/**
 * A full model that is returned from a call to the DB
 * @export
 * @interface PACSdbReturnModel
 */
export interface PACSdbReturnModel {
    /**
     * 
     * @type {PACSsetupCore}
     * @memberof PACSdbReturnModel
     */
    info: PACSsetupCore;
    /**
     * 
     * @type {ModelsPacsSetupModelTime}
     * @memberof PACSdbReturnModel
     */
    timeCreated: ModelsPacsSetupModelTime;
    /**
     * 
     * @type {ModelsPacsSetupModelTime}
     * @memberof PACSdbReturnModel
     */
    timeModified: ModelsPacsSetupModelTime;
    /**
     * 
     * @type {string}
     * @memberof PACSdbReturnModel
     */
    message: string;
}

/**
 * Check if a given object implements the PACSdbReturnModel interface.
 */
export function instanceOfPACSdbReturnModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;
    isInstance = isInstance && "timeCreated" in value;
    isInstance = isInstance && "timeModified" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function PACSdbReturnModelFromJSON(json: any): PACSdbReturnModel {
    return PACSdbReturnModelFromJSONTyped(json, false);
}

export function PACSdbReturnModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PACSdbReturnModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': PACSsetupCoreFromJSON(json['info']),
        'timeCreated': ModelsPacsSetupModelTimeFromJSON(json['time_created']),
        'timeModified': ModelsPacsSetupModelTimeFromJSON(json['time_modified']),
        'message': json['message'],
    };
}

export function PACSdbReturnModelToJSON(value?: PACSdbReturnModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': PACSsetupCoreToJSON(value.info),
        'time_created': ModelsPacsSetupModelTimeToJSON(value.timeCreated),
        'time_modified': ModelsPacsSetupModelTimeToJSON(value.timeModified),
        'message': value.message,
    };
}

