/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The PACS Query model
 * @export
 * @interface PACSqueryCore
 */
export interface PACSqueryCore {
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    accessionNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    patientID?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    patientName?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    patientBirthDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    patientAge?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    patientSex?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    studyDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    studyDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    studyInstanceUID?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    modality?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    modalitiesInStudy?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    performedStationAETitle?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    numberOfSeriesRelatedInstances?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    instanceNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    seriesDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    seriesDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    seriesInstanceUID?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    protocolName?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    acquisitionProtocolDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    acquisitionProtocolName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PACSqueryCore
     */
    withFeedBack?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    then?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    thenArgs?: string;
    /**
     * 
     * @type {string}
     * @memberof PACSqueryCore
     */
    dblogbasepath?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PACSqueryCore
     */
    jsonResponse?: boolean;
}

/**
 * Check if a given object implements the PACSqueryCore interface.
 */
export function instanceOfPACSqueryCore(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PACSqueryCoreFromJSON(json: any): PACSqueryCore {
    return PACSqueryCoreFromJSONTyped(json, false);
}

export function PACSqueryCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): PACSqueryCore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessionNumber': !exists(json, 'AccessionNumber') ? undefined : json['AccessionNumber'],
        'patientID': !exists(json, 'PatientID') ? undefined : json['PatientID'],
        'patientName': !exists(json, 'PatientName') ? undefined : json['PatientName'],
        'patientBirthDate': !exists(json, 'PatientBirthDate') ? undefined : json['PatientBirthDate'],
        'patientAge': !exists(json, 'PatientAge') ? undefined : json['PatientAge'],
        'patientSex': !exists(json, 'PatientSex') ? undefined : json['PatientSex'],
        'studyDate': !exists(json, 'StudyDate') ? undefined : json['StudyDate'],
        'studyDescription': !exists(json, 'StudyDescription') ? undefined : json['StudyDescription'],
        'studyInstanceUID': !exists(json, 'StudyInstanceUID') ? undefined : json['StudyInstanceUID'],
        'modality': !exists(json, 'Modality') ? undefined : json['Modality'],
        'modalitiesInStudy': !exists(json, 'ModalitiesInStudy') ? undefined : json['ModalitiesInStudy'],
        'performedStationAETitle': !exists(json, 'PerformedStationAETitle') ? undefined : json['PerformedStationAETitle'],
        'numberOfSeriesRelatedInstances': !exists(json, 'NumberOfSeriesRelatedInstances') ? undefined : json['NumberOfSeriesRelatedInstances'],
        'instanceNumber': !exists(json, 'InstanceNumber') ? undefined : json['InstanceNumber'],
        'seriesDate': !exists(json, 'SeriesDate') ? undefined : json['SeriesDate'],
        'seriesDescription': !exists(json, 'SeriesDescription') ? undefined : json['SeriesDescription'],
        'seriesInstanceUID': !exists(json, 'SeriesInstanceUID') ? undefined : json['SeriesInstanceUID'],
        'protocolName': !exists(json, 'ProtocolName') ? undefined : json['ProtocolName'],
        'acquisitionProtocolDescription': !exists(json, 'AcquisitionProtocolDescription') ? undefined : json['AcquisitionProtocolDescription'],
        'acquisitionProtocolName': !exists(json, 'AcquisitionProtocolName') ? undefined : json['AcquisitionProtocolName'],
        'withFeedBack': !exists(json, 'withFeedBack') ? undefined : json['withFeedBack'],
        'then': !exists(json, 'then') ? undefined : json['then'],
        'thenArgs': !exists(json, 'thenArgs') ? undefined : json['thenArgs'],
        'dblogbasepath': !exists(json, 'dblogbasepath') ? undefined : json['dblogbasepath'],
        'jsonResponse': !exists(json, 'json_response') ? undefined : json['json_response'],
    };
}

export function PACSqueryCoreToJSON(value?: PACSqueryCore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccessionNumber': value.accessionNumber,
        'PatientID': value.patientID,
        'PatientName': value.patientName,
        'PatientBirthDate': value.patientBirthDate,
        'PatientAge': value.patientAge,
        'PatientSex': value.patientSex,
        'StudyDate': value.studyDate,
        'StudyDescription': value.studyDescription,
        'StudyInstanceUID': value.studyInstanceUID,
        'Modality': value.modality,
        'ModalitiesInStudy': value.modalitiesInStudy,
        'PerformedStationAETitle': value.performedStationAETitle,
        'NumberOfSeriesRelatedInstances': value.numberOfSeriesRelatedInstances,
        'InstanceNumber': value.instanceNumber,
        'SeriesDate': value.seriesDate,
        'SeriesDescription': value.seriesDescription,
        'SeriesInstanceUID': value.seriesInstanceUID,
        'ProtocolName': value.protocolName,
        'AcquisitionProtocolDescription': value.acquisitionProtocolDescription,
        'AcquisitionProtocolName': value.acquisitionProtocolName,
        'withFeedBack': value.withFeedBack,
        'then': value.then,
        'thenArgs': value.thenArgs,
        'dblogbasepath': value.dblogbasepath,
        'json_response': value.jsonResponse,
    };
}

