/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The SMDB file system service model
 * @export
 * @interface SMDBFsCore
 */
export interface SMDBFsCore {
    /**
     * 
     * @type {string}
     * @memberof SMDBFsCore
     */
    storepath: string;
}

/**
 * Check if a given object implements the SMDBFsCore interface.
 */
export function instanceOfSMDBFsCore(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "storepath" in value;

    return isInstance;
}

export function SMDBFsCoreFromJSON(json: any): SMDBFsCore {
    return SMDBFsCoreFromJSONTyped(json, false);
}

export function SMDBFsCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): SMDBFsCore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'storepath': json['storepath'],
    };
}

export function SMDBFsCoreToJSON(value?: SMDBFsCore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'storepath': value.storepath,
    };
}

