/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * For the most part, copied from
 * https://github.com/FNNDSC/pfcon/blob/87f5da953be7c2cc80542bef0e67727dda1b4958/pfcon/pfcon.py#L601-611
 * 
 * Provides information about the environment in which the service
 * is currently running.
 * @export
 * @interface SysInfoModel
 */
export interface SysInfoModel {
    /**
     * 
     * @type {string}
     * @memberof SysInfoModel
     */
    system?: string;
    /**
     * 
     * @type {string}
     * @memberof SysInfoModel
     */
    machine?: string;
    /**
     * Uname output, converted from object to list
     * @type {Array<string>}
     * @memberof SysInfoModel
     */
    uname?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SysInfoModel
     */
    platform?: string;
    /**
     * 
     * @type {string}
     * @memberof SysInfoModel
     */
    version: string;
    /**
     * Actually a NamedTuple but I'm not typing it out
     * @type {Array<any>}
     * @memberof SysInfoModel
     */
    memory: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof SysInfoModel
     */
    cpucount?: number;
    /**
     * Average system load over last 1, 5, and 15 minutes
     * @type {Array<any>}
     * @memberof SysInfoModel
     */
    loadavg: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof SysInfoModel
     */
    cpuPercent: number;
    /**
     * 
     * @type {string}
     * @memberof SysInfoModel
     */
    hostname?: string;
    /**
     * 
     * @type {string}
     * @memberof SysInfoModel
     */
    inet?: string;
}

/**
 * Check if a given object implements the SysInfoModel interface.
 */
export function instanceOfSysInfoModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "memory" in value;
    isInstance = isInstance && "loadavg" in value;
    isInstance = isInstance && "cpuPercent" in value;

    return isInstance;
}

export function SysInfoModelFromJSON(json: any): SysInfoModel {
    return SysInfoModelFromJSONTyped(json, false);
}

export function SysInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SysInfoModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'system': !exists(json, 'system') ? undefined : json['system'],
        'machine': !exists(json, 'machine') ? undefined : json['machine'],
        'uname': !exists(json, 'uname') ? undefined : json['uname'],
        'platform': !exists(json, 'platform') ? undefined : json['platform'],
        'version': json['version'],
        'memory': json['memory'],
        'cpucount': !exists(json, 'cpucount') ? undefined : json['cpucount'],
        'loadavg': json['loadavg'],
        'cpuPercent': json['cpu_percent'],
        'hostname': !exists(json, 'hostname') ? undefined : json['hostname'],
        'inet': !exists(json, 'inet') ? undefined : json['inet'],
    };
}

export function SysInfoModelToJSON(value?: SysInfoModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'system': value.system,
        'machine': value.machine,
        'uname': value.uname,
        'platform': value.platform,
        'version': value.version,
        'memory': value.memory,
        'cpucount': value.cpucount,
        'loadavg': value.loadavg,
        'cpu_percent': value.cpuPercent,
        'hostname': value.hostname,
        'inet': value.inet,
    };
}

