/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelsListenerModelTime } from './ModelsListenerModelTime';
import {
    ModelsListenerModelTimeFromJSON,
    ModelsListenerModelTimeFromJSONTyped,
    ModelsListenerModelTimeToJSON,
} from './ModelsListenerModelTime';
import type { XinetdCore } from './XinetdCore';
import {
    XinetdCoreFromJSON,
    XinetdCoreFromJSONTyped,
    XinetdCoreToJSON,
} from './XinetdCore';

/**
 * 
 * @export
 * @interface XinetdDBReturnModel
 */
export interface XinetdDBReturnModel {
    /**
     * 
     * @type {XinetdCore}
     * @memberof XinetdDBReturnModel
     */
    info: XinetdCore;
    /**
     * 
     * @type {ModelsListenerModelTime}
     * @memberof XinetdDBReturnModel
     */
    timeCreated: ModelsListenerModelTime;
    /**
     * 
     * @type {ModelsListenerModelTime}
     * @memberof XinetdDBReturnModel
     */
    timeModified: ModelsListenerModelTime;
    /**
     * 
     * @type {string}
     * @memberof XinetdDBReturnModel
     */
    message: string;
}

/**
 * Check if a given object implements the XinetdDBReturnModel interface.
 */
export function instanceOfXinetdDBReturnModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;
    isInstance = isInstance && "timeCreated" in value;
    isInstance = isInstance && "timeModified" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function XinetdDBReturnModelFromJSON(json: any): XinetdDBReturnModel {
    return XinetdDBReturnModelFromJSONTyped(json, false);
}

export function XinetdDBReturnModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): XinetdDBReturnModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': XinetdCoreFromJSON(json['info']),
        'timeCreated': ModelsListenerModelTimeFromJSON(json['time_created']),
        'timeModified': ModelsListenerModelTimeFromJSON(json['time_modified']),
        'message': json['message'],
    };
}

export function XinetdDBReturnModelToJSON(value?: XinetdDBReturnModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': XinetdCoreToJSON(value.info),
        'time_created': ModelsListenerModelTimeToJSON(value.timeCreated),
        'time_modified': ModelsListenerModelTimeToJSON(value.timeModified),
        'message': value.message,
    };
}

