/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The core data model
 * @export
 * @interface XinetdCore
 */
export interface XinetdCore {
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    servicePort: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    tmpDir: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    logDir: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    dataDir: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    listener: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    patientMapDir: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    studyMapDir: string;
    /**
     * 
     * @type {string}
     * @memberof XinetdCore
     */
    seriesMapDir: string;
}

/**
 * Check if a given object implements the XinetdCore interface.
 */
export function instanceOfXinetdCore(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "servicePort" in value;
    isInstance = isInstance && "tmpDir" in value;
    isInstance = isInstance && "logDir" in value;
    isInstance = isInstance && "dataDir" in value;
    isInstance = isInstance && "listener" in value;
    isInstance = isInstance && "patientMapDir" in value;
    isInstance = isInstance && "studyMapDir" in value;
    isInstance = isInstance && "seriesMapDir" in value;

    return isInstance;
}

export function XinetdCoreFromJSON(json: any): XinetdCore {
    return XinetdCoreFromJSONTyped(json, false);
}

export function XinetdCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): XinetdCore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'servicePort': json['servicePort'],
        'tmpDir': json['tmpDir'],
        'logDir': json['logDir'],
        'dataDir': json['dataDir'],
        'listener': json['listener'],
        'patientMapDir': json['patient_mapDir'],
        'studyMapDir': json['study_mapDir'],
        'seriesMapDir': json['series_mapDir'],
    };
}

export function XinetdCoreToJSON(value?: XinetdCore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'servicePort': value.servicePort,
        'tmpDir': value.tmpDir,
        'logDir': value.logDir,
        'dataDir': value.dataDir,
        'listener': value.listener,
        'patient_mapDir': value.patientMapDir,
        'study_mapDir': value.studyMapDir,
        'series_mapDir': value.seriesMapDir,
    };
}

