/* tslint:disable */
/* eslint-disable */
/**
 * pfdcm
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { XinetdCore } from './XinetdCore';
import {
    XinetdCoreFromJSON,
    XinetdCoreFromJSONTyped,
    XinetdCoreToJSON,
} from './XinetdCore';

/**
 * 
 * @export
 * @interface XinetdDBPutModel
 */
export interface XinetdDBPutModel {
    /**
     * 
     * @type {XinetdCore}
     * @memberof XinetdDBPutModel
     */
    info: XinetdCore;
}

/**
 * Check if a given object implements the XinetdDBPutModel interface.
 */
export function instanceOfXinetdDBPutModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "info" in value;

    return isInstance;
}

export function XinetdDBPutModelFromJSON(json: any): XinetdDBPutModel {
    return XinetdDBPutModelFromJSONTyped(json, false);
}

export function XinetdDBPutModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): XinetdDBPutModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': XinetdCoreFromJSON(json['info']),
    };
}

export function XinetdDBPutModelToJSON(value?: XinetdDBPutModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': XinetdCoreToJSON(value.info),
    };
}

